---
Name: artisan-config
---
Injector:
  ContentTypeMetaDataProvider:
    class: ArtisanStaticContentTypeMetaDataProvider
  AdaptableFormMetaDataProvider:
    class: ArtisanStaticContentTypeMetaDataProvider
ArtisanModelAdmin:
  managed_models:
    - ArtisanSection
